app/models/turma.py
from . import db

class Turma(db.Model):
    __tablename__ = "turma"
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100), nullable=False)
    horario_inicio = db.Column(db.Time, nullable=False)
    horario_fim = db.Column(db.Time, nullable=False)
    senha = db.Column(db.String(200), nullable=False)
    semestre = db.Column(db.Integer, nullable=False)
    
    # professor_id armazenará o ID do professor relacionado à turma.
    professor_id = db.Column(db.Integer, db.ForeignKey(
        'professor.id'), nullable=False)
    
    aulas = db.relationship('Aula', backref=db.backref('turma_aulas', lazy=True)) #1 to N

    # token_presenca

    def __repr__(self) -> str:
        return "<Turma %r>" % self.id

app/controllers/turmas_controller.py
from ..webapp import db
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user
from ..models import Turma, Aula
from datetime import datetime
from .aulas_controller import register_blueprint as register_aulas_blueprint

bp = Blueprint("turmas", __name__)
# registra blueprint de aulas passando turmas como pai
register_aulas_blueprint(bp)


@bp.route("/", methods=["GET"])
@login_required
def index():
    turmas = Turma.query.all()
    # user_type = session.get("user_type")

    print(f"Turmas: {turmas}")
    return render_template("turmas/index.jinja2", turmas=turmas, user=current_user)


@bp.route("/new", methods=["GET"])
@login_required
def new():
    return render_template("turmas/new.jinja2")


@bp.route("/validate", methods=["GET", "POST"])
@login_required
def validate():
    if request.method == "POST":
        # senha = request.form.get("senha")
        flash("Você foi matriculado em uma turma")
        return redirect(url_for("turmas.index"))

    return render_template("turmas/validate.jinja2")


@bp.route("/", methods=["POST"])
@login_required
def create():
    nome = request.form.get("nome")
    horario_inicio = request.form.get("horario_inicio")
    horario_fim = request.form.get("horario_fim")
    senha = request.form.get("senha")
    semestre = request.form.get("semestre")
    professor_id = current_user.id

    horario_inicio = datetime.strptime(horario_inicio, "%H:%M").time()
    horario_fim = datetime.strptime(horario_fim, "%H:%M").time()

    print(
        f"Form fields: {nome}, {horario_inicio}, {horario_fim}, {senha}, {semestre}, {professor_id}")

    new_turma = Turma(nome=nome, horario_inicio=horario_inicio, horario_fim=horario_fim, senha=senha,
                      semestre=semestre, professor_id=professor_id)
    try:
        db.session.add(new_turma)
        db.session.commit()
        flash("Turma criada")
    except Exception:
        db.session.rollback()
        flash("Erro ao criar turma")

    return redirect(url_for("turmas.index"))


@bp.route("/<int:turma_id>/show", methods=["GET"])
def show(turma_id):
    turma = db.get_or_404(Turma, turma_id)
    aulas = Aula.query.filter_by(turma_id=turma_id).all()
    if turma not in current_user.turmas:
        return redirect(url_for("turmas.matricular", turma_id=turma_id))
    return render_template("turmas/show.jinja2", turma=turma, aulas=aulas, user=current_user)


@bp.route("/<int:turma_id>/matricular", methods=["GET", "POST"])
def matricular(turma_id):
    print("tentou matricular")
    # se nao for aluno, nao pode prosseguir
    if current_user.tipo_usuario != "aluno":
        flash("Voce não pode realizar esta operação", category="error")
        return redirect(url_for("turmas.index"))

    turma = db.get_or_404(Turma, turma_id)
    print(turma)
    if request.method == "GET":
        print("matricular GET")
        return render_template("turmas/validate.jinja2", turma=turma)

    if request.method == "POST":
        print("matricular POST")
        senha = request.form.get("senha")
        print(f"fom senha: {senha} - senha turma: {turma.senha}")
        if senha == turma.senha:
            try:
                current_user.turmas.append(turma)
                db.session.commit()
                flash(f"Matriculou-se na Turma {turma.nome}")
                return redirect(url_for("turmas.show", turma_id=turma_id))
            except Exception as e:
                print(f"Algo deu erro: {e}")
                flash("Algo deu errado")
        else:
            flash("Senha invalida!", category="error")
            print("senha invalida")
            return render_template("turmas/validate.jinja2", turma=turma)

        return redirect(url_for("turmas.index"))

app/templates/turmas/index.jinja2
{% extends "./base.jinja2" %}
{% from 'bootstrap5/utils.html' import render_icon %}

{% block head %}
    {{ super() }}
    <style>
        .btn-add {
            position: fixed;
            bottom: 20px;
            right: 20px;
            z-index: 9999;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Turmas</h1>
        <div class="row row-col-1 row-cols-md-2 row-cols-lg-4">
            {% for turma in turmas %}
                <div class="col mb-4">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ url_for('turmas.show', turma_id=turma.id) }}">
                                <h5 class="card-title">{{ turma.nome }}</h5>
                            </a>
                            <p>Horário de início: {{ turma.horario_inicio.strftime('%H:%M') }}</p>
                            <p>Horário de Fim: {{ turma.horario_fim.strftime('%H:%M') }}</p>
                            <p class="card-text">Professor: {{ turma.professor_id }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if user.tipo_usuario == "professor" %}
            <div class="position-fixed bottom-0 end-0 p-3">
                <a href="{{ url_for('turmas.new') }}" class="btn btn-floating btn-lg btn-primary">
                    {{render_icon('plus') }} <span class="d-none d-xl-inline">Adicionar Turma</span>
                </a>
            </div>
        {% endif %}
    </div>
     
{% endblock %}

app/templates/turmas/new.jinja2
{% extends "./base.jinja2" %}


{% block header %}
<h1>{% block title %}Criar Turma{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST" action="{{ url_for('turmas.create') }}">
        <div class="form-floating mb-3">
            <input
                class="form-control"
                type="text"
                id="nome"
                name="nome"
                placeholder="Digite o nome da turma"
                required="true"
            />
            <label for="nome" class="form-label">Nome</label>
        </div>
        <div class="form-floating mb-3">
        <div class="mb-3">
            <label for="horario_inicio" class="form-label">Horario Inicio</label>
            <input
                class="form-control"
                type="time"
                id="horario_inicio"
                name="horario_inicio"
                placeholder="Selecione o horario que começa a aula"
                required="true"
            />
        </div>
        <div class="form-floating mb-3">
        <div class="mb-3">
            <label for="horario_fim" class="form-label">Horario Fim</label>
            <input
                class="form-control"
                type="time"
                id="horario_fim"
                name="horario_fim"
                placeholder="Selecione o horario que termina a aula"
                required="true"
            />
        </div>
        <div class="mb-3">
            <label for="senha" class="form-label">Senha</label>
            <input
                class="form-control"
                type="password"
                id="senha"
                name="senha"
                placeholder="Digite a senha da turma"
                required="true"
            />
        </div>
        <div class="mb-3">
            <label for="semestre" class="form-label">Semestre</label>
            <input
                class="form-control"
                type="number"
                min="1"
                max="15"
                id="semestre"
                name="semestre"
                placeholder="Digite o semestre"
                required="true"
            />
        </div>
        <button type="submit">Criar</button>
    </form>
</div>

{% endblock %}

app/templates/turmas/show.jinja2
{% extends "./base.jinja2" %}
{% from 'bootstrap5/utils.html' import render_icon %}


{% block header %}
<h1>{% block title %}Criar Turma{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
    <h3>Turma {{ turma.nome }}</h3>
    <p>Semestre: {{ turma.semestre }}</p>
    <b>Aulas:</b>
    <div class="row row-col-1 row-cols-md-2 row-cols-lg-4">
        {% for aula in aulas %}
            <div>
                <div class="card">
                    <div class="card-body">
                        {% include 'aulas/show.jinja2' %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if user.tipo_usuario == "professor" %}
            <div class="position-fixed bottom-0 end-0 p-3">
                <a href="{{ url_for('turmas.aulas.new', turma_id=turma.id) }}" class="btn btn-floating btn-lg btn-primary">
                    {{render_icon('plus') }} <span class="d-none d-xl-inline">Adicionar Aula</span>
                </a>
            </div>
    {% endif %}
</div>

{% endblock %}

app/templates/turmas/validate.jinja2
{% extends "./base.jinja2" %}

{% block header %}
    <h1>{% block title %}Entrar em Turma{% endblock %}</h1>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Validar Senha da Turma {{ turma.nome }}</h1>
    <form method="POST" action="{{ url_for('turmas.matricular', turma_id=turma.id) }}">
        <div class="form-group">
            <label for="senha">Senha da Turma:</label>
            <input
                type="password"
                id="senha"
                name="senha"
                placeholder="Digite a senha da Turma"
                required="true"
            />
        </div>
        <button type="submit">Validar Senha</button>
    </form>
</div>
{% endblock %}